### ISSUE TITLE
Slow Performance 

### ISSUE THREAD

**Issue by atulkumar** [DanWahlin/Angular-ASPNET-Core-Seed#2]
Hi Dan,

I was looking into this seed solution but I found performance seems slow i.e. It's taking 8-9 sec to finish.I tried to run in Prod mode but still slow.
How can we improve performance?

**Comment by DanWahlin** [comment]
Let me know what you're referring to. The initial load time of the ASP.NET Kestrel server or something else? Once the server initializes I'm not seeing any lags in performance but there's definitely a wait time the first time the Kestrel server initializes (however that's a one-time wait in a "real" app since you'd leave it running of course). After that it should be very fast though.
