### ISSUE TITLE
Live reload?

### ISSUE THREAD

**Issue by jfpicard123** [DanWahlin/Angular-ASPNET-Core-Seed#3]
Thanks for this! Is there a way to enable some sort of live reload?

**Comment by DanWahlin** [comment]
I never got notified about this one - sorry about the big delay there. I'd love to get that in there but don't currently have any plans to research that particular feature. The challenge is that some people may run "ng serve" directly (which has live reload already) while others may serve up the Angular app via Kestrel. It'd be nice to get it in there at some point for the Kestrel side though.

I'm going to close this since I don't have the time to commit to it, but I'm happy to take a pull request if you find a simple solution for that (I'm assuming it's possible....just never looked into it).
